CREATE TRIGGER [tr_REGISTRATION_EXISTING_USER] ON REGISTRATION
AFTER INSERT, UPDATE
AS
    IF EXISTS(
         SELECT * FROM REGISTRATION WHERE
            R_EMAIL IN (SELECT R_EMAIL FROM inserted)
			OR
			R_USERNAME IN (SELECT R_USERNAME FROM inserted)
         HAVING COUNT(*) > 1)
    BEGIN
      RAISERROR('THIS RECORD ALREADY EXISTS', 10, 1)
      ROLLBACK
    END

