-- This sql file is used to drop all the tables from the db.

DROP TABLE FAQ
DROP TABLE REGISTRATION
DROP TABLE TICKET
DROP TABLE EMPLOYEE
DROP TABLE COMP_POLICY
GO
DROP PROC ADD_FAQ
DROP PROC RESET_FAQ
GO