CREATE TRIGGER [tr_EMPLOYEE_EXISTING_USER] ON REGISTRATION
AFTER INSERT, UPDATE
AS
    IF EXISTS(
         SELECT * FROM EMPLOYEE WHERE
            EMP_EMAIL IN (SELECT R_EMAIL FROM inserted)
			OR
			EMP_USERNAME IN (SELECT R_USERNAME FROM inserted)
         HAVING COUNT(*) > 1)
    BEGIN
      RAISERROR('THIS RECORD ALREADY EXISTS', 10, 1)
      ROLLBACK
    END